package com.skyblockutils.utils;

import java.util.List;

public class FunFacts {
    public static List<String> funFacts = List.of(
            "Honey never spoils. Archaeologists have found edible honey in ancient Egyptian tombs.",
            "Bananas are berries, but strawberries are not.",
            "Octopuses have three hearts and blue blood.",
            "There’s a species of jellyfish that can live forever, called Turritopsis dohrnii.",
            "A day on Venus is longer than a year on Venus.",
            "Sloths can hold their breath longer than dolphins—up to 40 minutes.",
            "Wombat poop is cube-shaped.",
            "Sharks existed before trees.",
            "The shortest war in history lasted 38 minutes (Anglo-Zanzibar War, 1896).",
            "Sea otters hold hands when they sleep to keep from drifting apart.",
            "Cleopatra lived closer in time to the moon landing than to the construction of the Great Pyramid of Giza.",
            "There’s a basketball court inside the U.S. Supreme Court building nicknamed the 'Highest Court in the Land.'",
            "Some cats are allergic to humans.",
            "The inventor of the Pringles can is buried in one.",
            "You can’t hum while holding your nose closed.",
            "There’s a species of fungus called 'Zombie-ant fungus' that controls ants’ minds.",
            "A group of flamingos is called a 'flamboyance.'",
            "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
            "Otters have a favorite rock that they carry around and use to crack open shells.",
            "Pineapples take about two years to grow.",
            "Butterflies can taste with their feet.",
            "Scotland has 421 words for snow.",
            "There’s a species of spider called the Hobo spider.",
            "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
            "Some turtles can breathe through their butts.",
            "Humans and giraffes have the same number of neck vertebrae—seven.",
            "There’s a tiny species of frog that can fit on a coin called Paedophryne amauensis.",
            "The longest time between two twins being born is 87 days.",
            "Sea cucumbers fight by shooting out their own internal organs.",
            "There’s a planet made entirely of diamond, called 55 Cancri e.",
            "Sharks can live up to 500 years in the deep ocean (Greenland shark).",
            "Pigeons can recognize human faces.",
            "There’s a species of fish that can walk on land called the mudskipper.",
            "Butterflies have transparent wings with scales that give them color.",
            "A narwhal's tusk reveals its health and life history.",
            "Sloths can rotate their heads almost 360 degrees.",
            "Cows have best friends and get stressed when separated.",
            "The unicorn is the national animal of Scotland.",
            "There are more stars in the universe than grains of sand on Earth.",
            "Some bamboo species can grow up to 91 cm in a single day.",
            "A group of crows is called a 'murder.'",
            "Sea lions can bark like dogs.",
            "Jellyfish are 95% water.",
            "Humans share 60% of their DNA with bananas.",
            "Dogs’ noses are wet to help absorb scent chemicals.",
            "The longest hiccuping spree lasted 68 years.",
            "Sharks can detect one drop of blood in an Olympic-sized swimming pool.",
            "There’s a species of frog that can survive being frozen solid.",
            "The heart of a blue whale is the size of a small car.",
            "There’s a species of lizard that can squirt blood from its eyes.",
            "Some turtles can live to be more than 150 years old.",
            "Rats laugh when tickled.",
            "Wombats dig burrows up to 30 meters long."
    );
}
